const reporter = require('cucumber-html-reporter');

const options = {
  theme: 'bootstrap',
  jsonFile: 'reports/cucumber-report.json',   // JSON generated by Cucumber
  output: 'reports/cucumber-report.html',     // HTML output file
  reportSuiteAsScenarios: true,
  launchReport: true,                          // opens report in browser automatically
  metadata: {
    "App Version":"1.0.0",
    "Test Environment": "QA",
    "Browser": "Chrome",
    "Platform": "Windows 10",
  }
};

reporter.generate(options);

